baseurl = "https://doorbash.github.io/"
title = "Milad Doorbash"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
googleAnalytics = "UA-128176167-2"

[taxonomies]
  series = "series"

[params]
    author = "Milad Doorbash"
    avatar = "avatar.png"
    favicon = "avatar.png"
    description = "Game Programmer from Iran"
    publicationYear = "2019"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"

[[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/doorbash"

[[menu.main]]
    identifier = "email"
    name = "Email"
    url = "mailto:milad.doorbash@gmail.com"