baseurl = "http://doorbash.ir/"
title = "میلاد دورباش"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[taxonomies]
  series = "series"

[params]
    author = "میلاد دورباش"
    avatar = "avatar.jpg"
    favicon = "favicon.png"
    description = """
        مهندس نرم‌افزار، بازی‌ساز مستقل، اصفهان
    """
    publicationYear = "2019"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    name = "بلاگ"
    url = "/blog/"

[[menu.main]]
    identifier = "github"
    name = "گیتهاب"
    url = "https://github.com/doorbash"
    
[[menu.main]]
    identifier = "twitter"
    name = "توییتر"
    url = "https://twitter.com/doorbash"

[[menu.main]]
    identifier = "email"
    name = "ایمیل"
    url = "mailto:milad.doorbash@gmail.com"